================================================================================
GRADE
================================================================================

Total grade points: 50 points

Compilation:
CompanyHierarchyMain: 12 points
CompanyHierarchy: 35 points
CompanyHierarchyException: 1 point
Comments + Misc. : 2 points

--------------------------------------------------------------------------------

Your grade points: 44 points

Compilation: No Errors
CompanyHierarchyMain: 12 points
CompanyHierarchy: 29 points
CompanyHierarchyException: 1 point
Comments + Misc. : 2 points

Grading details

--------------------------------------------------------------------------------

CompanyHierarchy: 

Empty Tree checks: (-1)
a. removeEmployee() throws improper exception - should handle tree == NULL case.
b. getEmployeeWithTitle incorrect - returns non-null value
c. getSupervisorChain incorrect - returns non-null value 

1 employee tree checks: (-1)
a. getEmployeeWithTitle incorrect when employee isn't in tree 
b. getEmployeeInJoiningDateRange incorrect when employee isn't in tree

Exceptions checks: (-4)
a. getEmployee(..) didn't throw exception - should throw "Incorrect employee name for id!" exception
b. addEmployee(newEmployee,-11,"some supervisor") threw wrong exception type
c. removeEmployee(1, "some employee") throws wrong exception message "Cannot remove CEO of the company.."
   but should throw "Incorrect employee name for id!"
d. replaceEmployee(1, "some employee", newEmployee) threw wrong exception message for incorrrect id 
   and name provided for EXISTING employee - Message thrown: "Replacement title does not match existing title"
   instead of "Incorrect employee name for id!"
e. Similarly, replaceEmployee() throw wrong exception message for replacing employee that already exists. 
   Message thrown: ++Id already used!++ instead of "Replacing employee already exists on the Company Tree!"
f. Date parsing failed!
g. getEmployeeInJoiningDateRange("some string", "some string") didn't throw any exception
h. getCoWorkers(1, "some employee") didn't throw any exception at all.

